version: "1"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: backendgang
      POSTGRES_PASSWORD: backendgang
      POSTGRES_DB: backend
      PGPORT: 8000
    # ports:
    #   - 8000:8000

  wait-for-db:
    # check if database is up before execution of uvicorn
    image: atkrad/wait4x
    depends_on:
      - db
    command: tcp db:8000 -t 30s -i 500ms

  web:
    depends_on:
      wait-for-db:
        condition: service_completed_successfully
    build: .
    volumes:
      - ./:/code
    working_dir: /code/app
    command: uvicorn main:app --host 0.0.0.0 --reload --port 8001
    ports:
      - "0.0.0.0:8001:8001"
